### ISSUE TITLE
Unable to build/run the wallet

### ISSUE THREAD

**Issue by honungsburk** [Sphereon-Opensource/ssi-mobile-wallet#18]
The wallet looks great and I would love to be able to play around with it, unfortunately, I wasn't able to make it run.

Running `yarn run start` creates a QR code that when scanned with Expo Go does nothing.
When I run `expo start` the QR code works but I get stuck on this splash screen:

![Screenshot_20230102_102939_Expo Go](https://user-images.githubusercontent.com/21693578/210214382-0c88444b-f6a4-4a6f-8fac-6d461df01366.jpg)

There is no console output, so it is very difficult to understand the problem.

When trying to use `expo run:android` the build fails.

```
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.0.8).                 │
│   You are currently using expo-cli 6.0.6                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
› Building app...
Configuration on demand is an incubating feature.

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Configure project :expo-eas-client
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo-structured-headers
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo-updates-interface
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :expo

Using expo modules
  - unimodules-core (7.1.2)
  - expo-application (4.1.0)
  - expo-constants (13.1.1)
  - expo-dev-client (1.0.1)
  - expo-dev-launcher (1.0.1)
  - expo-dev-menu (1.0.1)
  - expo-eas-client (0.2.1)
  - expo-error-recovery (3.1.0)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-json-utils (0.3.0)
  - expo-keep-awake (10.1.1)
  - expo-linear-gradient (11.3.0)
  - expo-localization (13.0.0)
  - expo-manifests (0.3.1)
  - expo-modules-core (0.9.2)
  - expo-splash-screen (0.15.1)
  - expo-structured-headers (2.2.1)
  - expo-updates (0.13.4)


FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/frankhampusweslien/git/ssi-mobile-wallet/android/local.properties'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 28s
6 actionable tasks: 6 up-to-date
/Users/frankhampusweslien/git/ssi-mobile-wallet/android/gradlew exited with non-zero code: 1
Error: /Users/frankhampusweslien/git/ssi-mobile-wallet/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:145:9)
```

I've tried setting the `ANDROID_SDK_ROOT` environment variable both by defining it directly in the console and creating a local.properties file but it doesn't pick it up. I haven't tried changing the gradle version yet but maybe that would fix my problem?

Gradle

```
➜  android git:(develop) ✗ ./gradlew --version

------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Amazon.com Inc. 17.0.5+8-LTS)
OS:           Mac OS X 12.5.1 aarch64

```

Node:

```
➜  ssi-mobile-wallet git:(develop) ✗ nvm current
v14.21.2
```

Expo:

```
➜  ssi-mobile-wallet git:(develop) ✗ expo --version
6.0.8
```

**Comment by nklomp** [comment]
Hi @honungsburk .

Hmzz odd. We mainly test with JDK 11 and 13 versions. Next week when most developers are back in the office, we will finish the upgrade of the wallet to the latest React-Native version and also make test-flight versions available to interested parties.

Probably it is best to wait till the end of next week to have a testable version, as we will also look at removing the dev-client probably, and review the overall installation/dev setup documentation.

In the mean time, I would suggest to look at a bit of an older SDK version like 13 or 11 to build the Anroid/Java code with. Note that whenever you set environment variables, make sure these persist and are also available to newly spawned processes. 

Typically a simple check is to open a terminal and see whether you can call java and also whether it has the correct version:

````java -version````

**Comment by honungsburk** [comment]
Hi @nklomp, here is a short update:

I managed to install and run the app on my emulator by doing two things:

* Switch to java 11
* Place the `local.properties` file in this project's top folder, previously it was placed at `/android/local.properties`

Still haven't figured out how to run it on mobile using the ExpoGo app.

**Comment by honungsburk** [comment]
I connected my phone through USB and ran `yarn run android`: it worked 😄
